# vim: expandtab:ts=4:sw=4
"""Add password column

Revision ID: 2b809292d40
Revises: None
Create Date: 2015-01-18 19:23:55.274938

"""

# revision identifiers, used by Alembic.
revision = '2b809292d40'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
